version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(actions)"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/tests/integration"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps-playwright)"
    labels:
      - "dependencies"
      - "playwright"
    open-pull-requests-limit: 3
