name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  batch-fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    continue-on-error: true
    steps:
      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: javascript
      - name: Run fuzzers
        id: run
        if: steps.build.outcome == 'success'
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: batch
